### ISSUE TITLE
XLSX link dead

### ISSUE THREAD

**Issue by Kev63** [VitaSmith/vitali#1]
Hi. It seems the XLSX the software wants to download is dead. Here is the new one: **https://docs.google.com/spreadsheets/d/1HfI8elhzJW9XP9_A6KLx6AZpwP9vvWTal6i7NVwVWzs/export?format=xlsx**
I don't know how to compile a software so please do it. Thank you.

**Comment by VitaSmith** [comment]
This has been fixed.
